# Generated by Codex on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_scenario_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='scenarios/'),
        ),
    ]
