# Generated by Codex on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenario_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='archive_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='archive_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_stage_scenarios', to='catalog.scenariostatus'),
        ),
    ]
