# Generated by Django 6.0.1 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0002_alter_executionstatus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleexecution",
            name="rows_affected_consistent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
