# Generated by Django 6.0.1 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0003_ruleexecution_rows_affected_consistent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruleexecution",
            name="rows_affected_consistent",
        ),
        migrations.AddField(
            model_name="ruleexecution",
            name="execution_mode",
            field=models.CharField(default="inconsistent", max_length=20),
        ),
    ]
